Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  
  config.vm.define "node1" do |subconfig|
     subconfig.vm.hostname = "node1.dimzrio.com"
     subconfig.vm.network "private_network", ip: "192.168.56.101", name: "vboxnet0", adapter: 4

     subconfig.vm.provider "virtualbox" do |vbox|
          vbox.name = "node1"
          vbox.memory = 2048
          vbox.cpus = 2
     end
  end

  config.vm.define "node2" do |subconfig|
     subconfig.vm.hostname = "node2.dimzrio.com"
     subconfig.vm.network "private_network", ip: "192.168.56.102", name: "vboxnet0", adapter: 4

     subconfig.vm.provider "virtualbox" do |vbox|
          vbox.name = "node2"
          vbox.memory = 2048
          vbox.cpus = 2
     end
  end

end
