Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  
  config.vm.define "node1" do |subconfig|
    subconfig.vm.hostname = "node1.dimzrio.com"
    subconfig.vm.network "private_network", ip: "192.168.56.101", name: "vboxnet0", adapter: 4

    subconfig.vm.provider "virtualbox" do |vbox|
      vbox.name = "node1"
      vbox.memory = 2048
      vbox.cpus = 2
      unless File.exist?('./secondDisk-node1.vdi')
        vbox.customize ['createhd', '--filename', './secondDisk-node1.vdi', '--variant', 'Fixed', '--size', 1 * 1024]
      end
      vbox.customize ['storageattach', :id,  '--storagectl', 'IDE', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', './secondDisk-node1.vdi']
    end
  end

  config.vm.define "node2" do |subconfig|
    subconfig.vm.hostname = "node2.dimzrio.com"
    subconfig.vm.network "private_network", ip: "192.168.56.102", name: "vboxnet0", adapter: 4

    subconfig.vm.provider "virtualbox" do |vbox|
          vbox.name = "node2"
          vbox.memory = 2048
          vbox.cpus = 2
          unless File.exist?('./secondDisk-node2.vdi')
            vbox.customize ['createhd', '--filename', './secondDisk-node2.vdi', '--variant', 'Fixed', '--size', 1 * 1024]
          end
          vbox.customize ['storageattach', :id,  '--storagectl', 'IDE', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', './secondDisk-node2.vdi']
    end
  end

  config.vm.define "node3" do |subconfig|
    subconfig.vm.hostname = "node3.dimzrio.com"
    subconfig.vm.network "private_network", ip: "192.168.56.103", name: "vboxnet0", adapter: 4

    subconfig.vm.provider "virtualbox" do |vbox|
          vbox.name = "node3"
          vbox.memory = 2048
          vbox.cpus = 2
          unless File.exist?('./secondDisk-node3.vdi')
            vbox.customize ['createhd', '--filename', './secondDisk-node3.vdi', '--variant', 'Fixed', '--size', 1 * 1024]
          end
          vbox.customize ['storageattach', :id,  '--storagectl', 'IDE', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', './secondDisk-node3.vdi']
    end
  end

  config.vm.define "provisioning" do |subconfig|
    subconfig.vm.hostname = "provisioning.dimzrio.com"
    subconfig.vm.network "private_network", ip: "192.168.56.100", name: "vboxnet0", adapter: 4

    subconfig.vm.provider "virtualbox" do |vbox|
          vbox.name = "provisioning"
          vbox.memory = 1024
          vbox.cpus = 2
    end
    subconfig.vm.provision "shell", path: "https://gitlab.com/dimzrio/vagrant/raw/master/ceph/provisioning.sh"
  end

  config.vm.provision "shell", path: "https://gitlab.com/dimzrio/vagrant/raw/master/ceph/update.sh"
end
