Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  
  config.vm.define "nginx" do |nginx|
     nginx.vm.hostname = "nginx.dimzrio.com"
     nginx.vm.network "private_network", ip: "192.168.56.101", name: "vboxnet0", adapter: 4
     nginx.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
    
     nginx.vm.provider "virtualbox" do |vbox|
        vbox.gui = false
        vbox.memory = "1024"
        vbox.cpus = 1
        vbox.name = "centos7-nginx"
     end
  
     nginx.vm.provision "shell", inline: <<-SHELL
        yum -y install epel-release net-tools nano htop
        yum makecache
        yum -y install nginx
        systemctl restart nginx
        systemctl enable nginx
     SHELL

  end

end
