Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  NodeCount = 3
  (1..NodeCount).each do |i|
   config.vm.define "node#{i}" do |cfg|
     cfg.vm.hostname = "node#{i}.dimzrio.com"
     cfg.vm.network "private_network", ip: "192.168.56.10#{i}", name: "vboxnet0", adapter: 4
   
     cfg.vm.provider "virtualbox" do |vbox|
        vbox.gui = false
        vbox.memory = "1024"
        vbox.name = "node#{i}"
     end
     cfg.vm.provision "shell", inline: <<-SHELL
	yum -y install ntp ntpdate ntp-doc
	sudo cp /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
	ntpdate 0.id.pool.ntp.org
	hwclock --systohc
	systemctl enable ntpd.service
	systemctl start ntpd.service

	sed -i -e 's/#PubkeyAuthentication/PubkeyAuthentication/g' /etc/ssh/sshd_config
	sed -i -e 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
	systemctl restart sshd
     SHELL
   end
  end
end
