Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  
  config.vm.define "master" do |master|
     master.vm.hostname = "master.dimzrio.com"
     master.vm.network "private_network", ip: "192.168.56.101", name: "vboxnet0", adapter: 4
   
     master.vm.provider "virtualbox" do |vbox|
        vbox.gui = false
        vbox.memory = "1024"
        vbox.name = "centos7-master"
     end
  end

end
