Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"

  config.vm.define "ipfs-01" do |subconfig|
     subconfig.vm.hostname = "ipfs-01.dimzrio.com"
     subconfig.vm.network "private_network", ip: "192.168.7.101", name: "vboxnet1", adapter: 2

     subconfig.vm.provider "virtualbox" do |vbox|
          vbox.name = "ipfs-01"
          vbox.memory = 512
          vbox.cpus = 2
     end
  end

  config.vm.define "ipfs-02" do |subconfig|
     subconfig.vm.hostname = "ipfs-02.dimzrio.com"
     subconfig.vm.network "private_network", ip: "192.168.7.102", name: "vboxnet1", adapter: 2

     subconfig.vm.provider "virtualbox" do |vbox|
          vbox.name = "ipfs-02"
          vbox.memory = 512
          vbox.cpus = 2
     end
  end

  config.vm.define "ipfs-03" do |subconfig|
     subconfig.vm.hostname = "ipfs-03.dimzrio.com"
     subconfig.vm.network "private_network", ip: "192.168.7.103", name: "vboxnet1", adapter: 2

     subconfig.vm.provider "virtualbox" do |vbox|
          vbox.name = "ipfs-03"
          vbox.memory = 512
          vbox.cpus = 2
     end
  end

  config.vm.provision "shell", path: "https://gitlab.com/dimzrio/vagrant/raw/master/ipfs/provisioning.sh"
end